<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<link rel="apple-touch-icon" sizes="180x180" href="www/favicon/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="www/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="www/favicon/favicon-16x16.png">
	<title></title>
    <style>
		* {
			box-sizing: border-box;
		}
	</style>
</head>
<body>
	<?= $body ?>
</body>
</html>
