<link rel="stylesheet" href="node_modules/photoswipe/dist/photoswipe.css">

<!-- Skin CSS file (styling of UI - buttons, caption, etc.)
     In the folder of skin CSS file there are also:
     - .png and .svg icons sprite,
     - preloader.gif (for browsers that do not support CSS animations) -->
<link rel="stylesheet" href="node_modules/photoswipe/dist/default-skin/default-skin.css">

<link rel="stylesheet" href="https://popper.js.org/css/popper.css" />
<link rel="stylesheet" href="www/css/pina.css" />
