<?php
/** @var $file1 int */
/** @var $images array */
?>
<!doctype html>
<html>
<head>
    <style>
        html, body, div#app {
            height: 100%;
            background: dimgrey;
        }

        img {
            max-width: 100%;
            max-height: 100%;
            width: 100%;
            height: 100%;
            object-fit: contain;
            background-size: contain;
            background-repeat: no-repeat;
            background-position: 50% 50%;
        }
    </style>
</head>
<body>
<div id="app">
    <img src="ShowOriginal?file=<?= $file1 ?>"
         style="background-image: url(ShowThumb?file=<?= $file1 ?>);"
    />
</div>
<script src="www/js/PreviewController.js"></script>
<script>
	var images = <?= $images ?>;
    new PreviewController(images);
</script>
</body>
</html>
