<?php
/** @var $file1 int */
/** @var $images array */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="apple-touch-icon" sizes="180x180" href="www/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="www/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="www/favicon/favicon-16x16.png">
    <style>
        html, body, div#app {
            height: 100%;
            background: dimgrey;
            margin: 0;
        }

        img {
            max-width: 100%;
            max-height: 100%;
            width: 100%;
            height: 100%;
            object-fit: contain;
            background-size: contain;
            background-repeat: no-repeat;
            background-position: 50% 50%;
        }
    </style>
    <title>Preview</title>
    <meta property="og:image" content="ShowThumb?file=<?= $file1 ?>" />
</head>
<body>
<div id="app">
    <img src="ShowOriginal?file=<?= $file1 ?>"
         style="background-image: url(ShowThumb?file=<?= $file1 ?>);"
    />
</div>

<script src="node_modules/swiped-events/src/swiped-events.js"></script>
<script src="www/js/PreviewController.js"></script>
<script>
	const images = <?= $images ?>;
    new PreviewController(images);
</script>
<script src="www/js/TagFiles.js"></script>
<script>
    new TagFiles();
</script>
</body>
</html>
