<?php
/** @var $head string */
/** @var $sources Source[] */
/** @var $body string */
/** @var $foot string */
/** @var $scripts string */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <base href="<?= $this->baseHref ?>"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"/>
    <title>Pinacotheque</title>
    <link rel="apple-touch-icon" sizes="180x180" href="www/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="www/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="www/favicon/favicon-16x16.png">
	<?= $head ?>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="www/css/pina.css"/>
</head>
<body>
<div class="columns">
    <div class="column is-one-sixth">
        <aside class="menu">
            <p class="menu-label">
                <img src="www/favicon/favicon-32x32.png" align="absmiddle"/>
                &nbsp;
                Pinacotheque
            </p>
            <ul class="menu-list">
                <!--                <li><a href="PhotoTimeline">Photo Timeline</a></li>-->
                <li><a href="Sources">Browse DB</a></li>
                <li>
                    <div class="level">
                        <!-- Left side -->
                        <div class="level-left">
                            <div class="level-item">
                                Sources
                            </div>
                        </div>
                        <div class="level-right">
                            <p class="level-item">
                                <a href="AddSource">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </p>
                        </div>
                    </div>
                </li>
				<?php foreach ($sources as $source): ?>
                    <li>
                        <nav class="level">
                            <!-- Left side -->
                            <div class="level-left">
                                <div class="level-item">
                                    <a href="Sources?action=setSource&id=<?= $source->id ?>"
                                       title="<?= $source->path ?>" style="overflow: hidden">
										<?= $source->name ?>
                                    </a>
                                </div>
                            </div>
                            <div class="level-right" style="align-items: end">
                                <p class="level-item">
                                    <a href="EditSource?source=<?= $source->id ?>">
                                        <i class="fa fa-cog"></i>
                                    </a>
                                </p>
                            </div>
                        </nav>
                    </li>
				<?php endforeach; ?>
                <li><a href="About">About</a></li>
            </ul>
        </aside>
        <div id="sidebar" style="position: sticky; top: 0;">

        </div>
    </div>
    <div class="column">
		<?= $this->s($body) ?>
    </div>
</div>
<?= $foot ?>
<?= $this->s($scripts) ?>
</body>
</html>
